### ISSUE TITLE
source .bashrc in passenger-app script

### ISSUE THREAD

**Issue by rraallvv** [mtgrosser/passenger-systemd#2]
I already have all the environment variables needed for the app to work exported from `~/.bashrc`, so maybe executing `source USER-PATH/.bashrc` in the `passenger-app` script would do in order to get the app running as a daemon instead of exporting the env vars again from that file.

However, I wonder is there is some side effect or unintended consequence of doing it in that way.

Does anyone know whether that's a good idea (or even recommended) for setting up all the needed environment variables?

**Comment by driehuis** [comment]
In general, .profile and .bashrc are geared toward setting up an environment for interactive use, so if you can get your app to work without sourcing `.bashrc` my recommendation would be not to source `.bashrc`.

That said, I've seen many deployments which source `.bashrc` just because that's where an interactive setup of, say, `rbenv` or `rvm` leaves the magic to hook up the ruby version manager by default. It's not wrong, it's just brittle.

Not sure if the issue tracker is the best venue for this discussion BTW.

**Comment by mtgrosser** [comment]
I agree with @driehuis, as the apps are run as system services, they should run mostly independent of some user's shell profiles. That being said, this repo provides just example files which you're free to adapt to your local setup. I'd however recommend to put any environment configurations in a separate file, to make them reproducible.

Actually, an earlier version of passenger-systemd required a so-called env file, which is a feature supported by systemd:

https://github.com/mtgrosser/passenger-systemd/blob/cdb4dff8fbd41c12ef39657e610eaa3277201979/passenger%40.service#L12

There even was a rake task to generate it, which hasn't been removed yet, although it's no longer used. If you need special environment settings for your apps to run, it might be a way to go. Just change your local service file accordingly.

**Comment by rraallvv** [comment]
@driehuis @mtgrosser thanks for the tip, it's very much appreciated. I'm closing this then ;)
